### PR TITLE
Enhancement/responsive

### LINKED ISSUE #15: Fix Layout for different device screens
For example, Onboarding screen looks broken on iPad.

### LINKED ISSUE #57: Responsive font and spacing for bigger screens like iPad
Install and refactor all style with this packages: https://github.com/nirsky/react-native-size-matters
The package will help to handle to scale font and space for tablets.

This is a separate issue from #15 as it will take time

### PR DESCRIPTION
**Pull request by tsejerome**
Resolves #15
Resolves #57

### CODE REVIEW

**Comment by tsejerome** [comment]
Currently tested on iPad Pro 9.7 Inch and iPhone 13
Will test on Android and iPhone 8 tomorrow before requesting @aguycalled review

**Comment by aguycalled** [comment]
image

Device: iPad

The 12 words should fit in one screen view without needing to scroll

Same with the text fields to confirm the words of the next step:

image

**Comment by aguycalled** [comment]
On IPad/iPad Pro (9 inches)/iPad Pro (12,9 inches), the onboarding screen does not fit the whole text:

image

Issue is also visible, although better layer out, on iPad Air/iPad Pro (11 inch):

image

While iPhone 8 does fit it:

image

Which makes me think there is something wrong with the ratio/scaling?

**Comment by aguycalled** [comment]
iPad mini and iPad Pro (12,9 inches) have the issue we commented about scrolling the onboarding, where the middle card is ignored:

https://user-images.githubusercontent.com/24814046/164030401-35eff588-5c50-43eb-94f2-b5c25b533dd8.mp4

I think this is fixed by using

```
snapToOffsets={[...Array(OnBoarding.length)].map((x, i) => (i * (width-80)))}
```

instead of 

```
snapToInterval={scale(width - 80)}
```

**Comment by aguycalled** [comment]
everything else looking good on iOS devices. haven't tried android yet

**Comment by tsejerome** [comment]
For onboarding screen, the reason for this to happen is because of the dimension differences of iPhone and iPad, I think for better asethetics, we will add a maxHeight to the Card


**Relevant Fixes:**
image
image

Also added some asthetics update on onboarding
image

**Comment by tsejerome** [comment]
For onBoarding screen button covering text issue, let's update it accordingly after the content is set

**Review by aguycalled — APPROVED** [review]

**Pull request merged**
