### PR TITLE
Fiat Exchange rate and Select Currency Setting Screen

### PR DESCRIPTION
**Pull request by paulayo93**
the exchange rate feature
reorganize some folders and files

### CODE REVIEW

**Comment by paulayo93** [comment]
Am done with it now

**Comment by aguycalled** [comment]
Reviewed the changes functionally. Some minor comments:
- Tokens and NFTs do not have the same value as NAV. So far I would leave them those without a FIAT value.
- It would be ideal, if the send screen shows the FIAT value of the amount to send.
- I think there should be an option in the Currency screen to not show any conversion.

I still need to go through all the code changes

**Comment by paulayo93** [comment]
Can I start making the changes now or I should wait till you  are done?

**Comment by aguycalled** [comment]
In the currency screen, since the top bar is not fixed, when a currency is selected, it requires to scroll back up to hit the back button. I'd suggest to keep the top bar fixed or to exit the screen once a currency is selected.

**Comment by paulayo93** [comment]
> In the currency screen, since the top bar is not fixed, when a currency is selected, it requires to scroll back up to hit the back button. I'd suggest to keep the top bar fixed or to exit the screen once a currency is selected.

Alright I will work on the reviews

Thanks

**Comment by paulayo93** [comment]
I am done the review @aguycalled

**Comment by paulayo93** [comment]
@aguycalled updated the commit with changes. All changes are included in it

**Pull request merged**
