### PR TITLE
adding toasty on tap to copy

### PR DESCRIPTION
**Pull request by tsejerome**

### CODE REVIEW

**Comment by aguycalled** [comment]
should we extend the touchable area? intuitively I tend to try to tap the qr code or address, as the Tap to Copy does not really look like a button

**Comment by tsejerome** [comment]
Sure, let me do later

**Comment by aguycalled** [comment]
if tapped multiple times, the old toast does not disappear

image

should do `toast.hideAll();` before showing it

**Comment by tsejerome** [comment]
image
How about we do it like this. I checked several other crypto apps like Binance, they won't allow full page click, but instead tap a particular line or icon

**Comment by tsejerome** [comment]
resolves #88

**Review by aguycalled — APPROVED** [review]

**Pull request merged**
